/// Flutter icons CardIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardIcons
///      fonts:
///       - asset: fonts/CardIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CardIcons {
  CardIcons._();

  static const _kFontFam = 'CardIcons';
  static const String? _kFontPkg = null;

  static const IconData sun = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
